---
title: "Myth of Black IQ Inferiority Response"
description: |
  My reaction to Johnathan Crane's article
author:
  - name: Patrick Ihejirika 
    url: https://www.linkedin.com/in/patrick-ihejirika-1a3a60193/
    affiliation: Brooklyn College MARC Program
    affiliation_url: https://example.com/spacelysprokets
date: 08-26-2020
output:
  distill::distill_article:
    self_contained: false
---

# Exploring the Myth of Scientific Support for the Theory of Black Intellectual Inferiority: My Reaction broken down in specific sections

The Theoretical Flaws of the Hereditarian Argument

Crane employs a solid example of a basketball coach preferring taller player to display a type of causal relationship between the tendency of environments reacting to the genetics of individuals. I have some reservations about this however. This is because, while the amount of people who play basketball professionally happen to be tall, that doesn't necessarily mean that those same people are better at basketball than people who are relatively short. I believe that the term better here, similarly to the term intelligent needs to be operationalized to better be analyzed, or better yet altered completely to identify people as being intelligent as people who are the most competent at doing a specific task, or a series of specific tasks to achieve a specific goal. The specificities should depend on the situation at hand of course. That way, the firing of neural signals can be measured and compared to other people and based off that the person or in this case, the average speed of the neural signal of a community should be compared to the average speed of neural signals of others in the same community, but varying socioeconomic class which should then be repeated to people of other communities, but within the same region and compared. Doing all of this should identify if there are any differences between the groups being analyzed, but shouldn't display whether or not those differences are negative/harmful or positive/beneficial, so it should be compared to a standard identified by compiling the average  neural signal speed of all participants involved to receive a population average to then be compared with the average speed of each group. If the average of a group is above the population average, the group should be deemed competent and if not, they should be deemed incompetent. I hypothesize that the results of Crane's argument should be validated because there will be a variety of underlying differences within and between racial groups because the main determinence of competence at a task is experience doing the actual task as opposed to racial genetics. Please let me know if this is wrong.Thanks for reading!

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```



